# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('creditcard.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[ 2.53634674e+00  1.37815522e+00 -3.38320770e-01 ...  1.33558377e-01
  -2.10530535e-02  1.49620000e+02]
 [ 1.66480113e-01  4.48154078e-01  6.00176493e-02 ... -8.98309914e-03
   1.47241692e-02  2.69000000e+00]
 [ 1.77320934e+00  3.79779593e-01 -5.03198133e-01 ... -5.53527940e-02
  -5.97518406e-02  3.78660000e+02]
 ...
 [-3.24963981e+00 -5.57828125e-01  2.63051512e+00 ...  4.45477214e-03
  -2.65608286e-02  6.78800000e+01]
 [ 7.02510230e-01  6.89799168e-01 -3.77961134e-01 ...  1.08820735e-01
   1.04532821e-01  1.00000000e+01]
 [ 7.03337367e-01 -5.06271240e-01 -1.25456788e-02 ... -2.41530880e-03
   1.36489143e-02  2.17000000e+02]]


In [4]:
print(y)

[0 0 0 ... 0 0 0]


### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [6]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [7]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [11]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [12]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
7121/7121 [==============================] - 9s 1ms/step - loss: 0.0476 - accuracy: 0.9983
Epoch 2/100
7121/7121 [==============================] - 7s 930us/step - loss: 0.0068 - accuracy: 0.9989
Epoch 3/100
7121/7121 [==============================] - 7s 925us/step - loss: 0.0040 - accuracy: 0.9995
Epoch 4/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0043 - accuracy: 0.9993
Epoch 5/100
7121/7121 [==============================] - 6s 848us/step - loss: 0.0034 - accuracy: 0.9994
Epoch 6/100
7121/7121 [==============================] - 7s 932us/step - loss: 0.0033 - accuracy: 0.9994
Epoch 7/100
7121/7121 [==============================] - 7s 931us/step - loss: 0.0033 - accuracy: 0.9994
Epoch 8/100
7121/7121 [==============================] - 6s 900us/step - loss: 0.0033 - accuracy: 0.9994
Epoch 9/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0031 - accuracy: 0.9994
Epoch 10/100
7121/7121 [==============================] - 6s 

7121/7121 [==============================] - 7s 951us/step - loss: 0.0026 - accuracy: 0.9995
Epoch 79/100
7121/7121 [==============================] - 6s 824us/step - loss: 0.0027 - accuracy: 0.9995
Epoch 80/100
7121/7121 [==============================] - 6s 897us/step - loss: 0.0030 - accuracy: 0.9994
Epoch 81/100
7121/7121 [==============================] - 7s 935us/step - loss: 0.0028 - accuracy: 0.9995
Epoch 82/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0028 - accuracy: 0.9996
Epoch 83/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0029 - accuracy: 0.9995
Epoch 84/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0026 - accuracy: 0.9995
Epoch 85/100
7121/7121 [==============================] - 7s 1ms/step - loss: 0.0027 - accuracy: 0.9995
Epoch 86/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0030 - accuracy: 0.9994
Epoch 87/100
7121/7121 [==============================] - 8s 1ms/step

# Part 4 - Prediction of Test Results

### Predicting the Test set results

In [13]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[56848    13]
 [   20    81]]


0.999420666409185